# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6684ff020d60b48f827b3b8867dd9008a3362433d513b459f1bbdd21723db7356aeb4b16eb65d6f1b79b7acdc86b053ba83040e90caaa4ac2ce4b4d928666b45

test:
  secret_key_base: bbcf590ee3faf3a8fb5c0e6b3e7f5016d8a4690ec55cf9f73892f0a4a10f8894563a7f9d38457baa1081919c74bed1bcda909c336ea37e511458f8798d0d816c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
